### ISSUE TITLE
Úkol 1 mám hotový

### ISSUE THREAD

**Issue by JulieMysli** [JulieMysli/Programovani_v_pythonu_DU#1]
@KristynaSodomkova Podívej se mi na úkol1, prosím. Nemám všechny bonusy. Časově to nestíhám, tak odevzdávám aspoň toto. Díky moc. Julie Myslivcová

**Comment by KristynaSodomkova** [comment]
Nemam navrhy na zlepseni, uzaviram issue :) pokud bys chtela, muzeme reseni probrat na zoomu, napriklad pokud bys mela nejake konkretni dotazy. Mozna by ti byvalo ulehcilo zivot pridat metodu `__str__` do class Locality. Ale to jsou opravdu jen male navrhy. Nebo pouzit misto dictionary ENUM. nebo dataclass. Ale mas splneno, vse v poradku.

**Comment by JulieMysli** [comment]
Děkuji. Metodu __str__ jsem si tam teda přidala, o ENUM jsem slyšela včera poprvé z nedělního záznamu :-) Pro mě byl boj samotný proces nahrávání na Github. Tak se uvidíme na další lekci :)
