### ISSUE TITLE
Druhý úkol mám hotový

### ISSUE THREAD

**Issue by JulieMysli** [JulieMysli/Programovani_v_pythonu_DU#2]
@KristynaSodomkova Ahoj, nahrála jsem druhý vypracovaný úkol. Když mi program vrátí v části 1 více jak 20 výsledků, vypíše se mi v terminále jen prvních dvacet. Asi by to šlo nějak ošetřit, jen nevím jak, tak tajně doufám, jestli to bude ke splnění úkolu stačit :)

**Comment by KristynaSodomkova** [comment]
Ahoj Julie, za me je to super a mas splneno :)
